### ISSUE TITLE
Doesn't work in Firefox?

### ISSUE THREAD

**Issue by patriceckhart** [daniellienert/assetsource-pexels#4]
The plugin works perfectly in Chrome. 

In Firefox, however, the spinner rotates in the Inspector with the ImageInterface ...

**Comment by daniellienert** [comment]
Hey @patriceckhart - the package is a pure wrapper around the Pexels API implementing the Neos Assetsource Interfaces. There is no frontend code, or frontend-facing backend code implemented. I really doubt that the package can cause different behaviors with different browsers. 

If there is a bug, you might open that in the Neos core repo.
